preparing:
  raw_data_file: "data/train_data_final.xlsx"
  processed_path: "data"

etl:
  raw_data_file: "data/df_final_for_ml.csv"
  processed_path: "data"

train:
  processed_train: "data/df_processed_ml.csv" 
  model_path: "model/lightgbm_regression"

predict:
  model_path: "model/lightgbm_regression"
  processed_test: "data/data_to_predict.csv"
  predicted_file: "data/data_predicted.csv"
  export_result: True


